import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#00429c",
        "background": "#f9f9f9",
        "surface": "#f9f9f9",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "on-surface-variant": "#434652",
        "surface-tint": "#2b5bb5",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#002203",
        "outline-variant": "#c3c6d4",
        "secondary-fixed-dim": "#91d78a",
        "surface-variant": "#e2e2e2",
        "on-tertiary-container": "#7ecf79",
        "surface-dim": "#dadada",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "inverse-surface": "#2f3131",
        "on-tertiary-fixed": "#002204",
        "on-background": "#1a1c1c",
        "secondary-container": "#acf4a4",
        "tertiary-fixed-dim": "#88d982",
        "secondary": "#2a6b2c",
        "primary": "#003178",
        "tertiary": "#003f0b",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#307231",
        "on-tertiary-fixed-variant": "#005312",
        "on-primary-fixed": "#001945",
        "on-surface": "#1a1c1c",
        "primary-fixed-dim": "#b0c6ff",
        "error-container": "#ffdad6",
        "primary-container": "#0d47a1",
        "secondary-fixed": "#acf4a4",
        "on-secondary-fixed-variant": "#0c5216",
        "on-primary": "#ffffff",
        "outline": "#737783",
        "inverse-on-surface": "#f1f1f1",
        "tertiary-fixed": "#a3f69c",
        "primary-fixed": "#d9e2ff",
        "on-primary-container": "#a1bbff",
        "surface-container-highest": "#e2e2e2",
        "inverse-primary": "#b0c6ff",
        "surface-bright": "#f9f9f9",
        "tertiary-container": "#005914"
      },
      fontFamily: {
        "headline": ["Public Sans"],
        "body": ["Public Sans"],
        "label": ["Public Sans"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
};
export default config;
